const COLOR_VARIANT = {
  DEFAULT: 'default',
  // A
  // B
  BLUE: 'blue',
  BLUE_LOCHINVAR: 'blue-lochinvar',
  BLUE_PATTENS: 'blue-pattens',
  BLUE_DARK: 'blue-dark',
  BLUE_ICEBERG: 'blue-iceberg',
  BLUE_LIGHT: 'blue-light',
  // C
  CAUTION: 'caution',
  // D
  DANGER: 'danger',
  DEGRADE: 'degrade',
  // E
  EMPHASIS: 'emphasis',
  // F
  // G
  GREY: 'grey',
  GREY_ABEY: 'grey-abey',
  GREY_SOFT: 'grey-soft',
  GREY_DARK: 'grey-dark',
  GREY_DARKER: 'grey-darker',
  GREEN_PASTEL: 'green-pastel',
  // H
  // I
  // J
  // K
  // L
  LIGHT: 'light',
  // M
  // N
  // O
  ORANGE_LIGHT: 'orange-light',
  ORANGE_LIGHTER: 'orange-lighter',
  // P
  PRIMARY: 'primary',
  PRIMARY_DARK: 'primary-dark',
  PRIMARY_DARKER: 'primary-darker',
  PRIMARY_LIGHT: 'primary-light',
  // Q
  // R
  RED_MONZA: 'red-monza',
  // S
  SOFT: 'soft',
  SECONDARY: 'secondary',
  SUCCESS: 'success',
  // W
  WARNING: 'warning',
  WHITE: 'white',
};

export default COLOR_VARIANT;
